#!/usr/bin/env bash
# Display information about domain/subdomains

displayInfo() {
    local subdomain=$1
    local domain=$2

    local subRecord=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print $4}')
    local subIp=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print $5}')

    echo "The subdomain $subdomain is a $subRecord record and points to $subIp"
}

domain=$1
subdomain=$2

if [ "$#" -eq 1 ]
then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"
    do
        displayInfo "$sub" "$domain"
    done
elif [ "$#" -eq 2 ]
then
    displayInfo "$subdomain" "$domain"
fi
